version: '3.9'

# https://matomo.org/faq/how-to-install/faq_98/ Help will fix the issue of proxy.

services:

  matomo:
    container_name: matomo
    image: bitnami/matomo:${matomo_tag}
    restart: always
    user: "0:0"
    labels:
      service: matomo
    volumes:
      - matomo_log_vol:/var/www/html/logs
      - ${matomo_data_path}/var/www/html:/var/www/html
    environment:
      - MATOMO_HOST=${matomo_host}
      - MATOMO_DATABASE_HOST=${db_host}
      - MATOMO_DATABASE_PORT_NUMBER=3306
      - MATOMO_DATABASE_NAME=${db_dbname}
      - MATOMO_DATABASE_USER=${db_username}
      - MATOMO_DATABASE_PASSWORD=${db_password}
    ports:
      - ${matomo_port}:8080

  filebeat:
    container_name: filebeat
    image: ${acr_login_server}.azurecr.io/filebeat:${filebeat_tag}
    user: root
    stdin_open: true
    tty: true
    restart: always
    labels:
      service: filebeat
    volumes:
      - filebeat_vol:/var/log
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/cloud-init-output.log:/var/log/hostlogs/cloud-init/cloud-init-output.log
      - matomo_log_vol:/var/log/filelogs/matomo
    environment:
      - ES_HOSTS=${es_hosts}
      - ES_USERNAME=${es_username}
      - ES_PASSWORD=${es_password}
      - APP_CUSTOMER=${app_customer}
      - APP_OWNER=${app_owner}
      - APP_EMAIL=${app_email}
      - APP_ENV=${app_env}
      - APP_DEPLOYMENT=${app_deployment}
      - APP_REPO=${app_repo}
      - APP_MODULE=${app_module}
      - APP_RESOURCE_GROUP=${app_resource_group}

volumes:
  filebeat_vol:
    driver: local
  matomo_log_vol:
    driver: local
