version: "3.9"

services:
  rancher:
    container_name: rancher
    image: rancher/rancher:${rancher_tag}
    restart: unless-stopped
    user: "0:0"
    privileged: true
    labels:
      service: rancher
    volumes:
      - ${rancher_data_path}:/var/lib/rancher
    ports:
      - ${rancher_service_port}:443
      - 80:80

  filebeat:
    container_name: filebeat
    image: ${acr_login_server}.azurecr.io/filebeat:${filebeat_tag}
    user: root
    restart: always
    labels:
      service: filebeat 
    volumes:
      - filebeat_vol:/var/log
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/cloud-init-output.log:/var/log/hostlogs/cloud-init/cloud-init-output.log
      - rancher_log_vol:/var/log/filelogs/rancher
    environment:
      - ES_HOSTS=${es_hosts}
      - ES_USERNAME=${es_username}
      - ES_PASSWORD=${es_password}
      - APP_CUSTOMER=${app_customer}
      - APP_OWNER=${app_owner}
      - APP_EMAIL=${app_email}
      - APP_ENV=${app_env}
      - APP_DEPLOYMENT=${app_deployment}
      - APP_REPO=${app_repo}
      - APP_MODULE=${app_module}
      - APP_RESOURCE_GROUP=${app_resource_group}

volumes:
  rancher_log_vol:
    driver: local
  filebeat_vol:
    driver: local