version: "3.9"
services:
  metabase:
    container_name: metabase
    image: metabase/metabase:${metabase_tag}
    restart: always
    labels:
      service: metabase
    volumes:
      - ${metabase_data_path}:/metabase-data
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=${metabase_db_name}
      - MB_DB_USER=${metabase_db_user}
      - MB_DB_PASS=${metabase_db_password}
      - MB_DB_HOST=${metabase_db_host}
      - MB_DB_PORT=5432
      - MB_EMOJI_IN_LOGS=false
      - MB_COLORIZE_LOGS=false
      - JAVA_OPTS=-Dlog4j.configurationFile=file:///metabase-data/configs/logging/log4j2.xml
    ports:
      - ${metabase_port}:3000

  filebeat:
    container_name: filebeat
    image: ${acr_login_server}.azurecr.io/filebeat:${filebeat_tag}
    user: root
    restart: always
    labels:
      service: filebeat 
    volumes:
      - filebeat_vol:/var/log
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/cloud-init-output.log:/var/log/hostlogs/cloud-init/cloud-init-output.log
    environment:
      - ES_HOSTS=${es_hosts}
      - ES_USERNAME=${es_username}
      - ES_PASSWORD=${es_password}
      - APP_CUSTOMER=${app_customer}
      - APP_OWNER=${app_owner}
      - APP_EMAIL=${app_email}
      - APP_ENV=${app_env}
      - APP_DEPLOYMENT=${app_deployment}
      - APP_REPO=${app_repo}
      - APP_MODULE=${app_module}
      - APP_RESOURCE_GROUP=${app_resource_group}

volumes:
  filebeat_vol:
    driver: local