version: "3.9"
services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3:${nexus_tag}
    restart: always
    user: root
    labels:
      service: nexus
    volumes:
      - ${nexus_data_path}:/nexus-data
      - nexus_log_vol:/nexus-data/log
    ports:
      - ${nexus_port}:8081

  filebeat:
    container_name: filebeat
    image: ${acr_login_server}.azurecr.io/filebeat:${filebeat_tag}
    user: root
    restart: always
    labels:
      service: filebeat 
    volumes:
      - filebeat_vol:/var/log
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/cloud-init-output.log:/var/log/hostlogs/cloud-init/cloud-init-output.log
      - nexus_log_vol:/var/log/filelogs/nexus
    environment:
      - ES_HOSTS=${es_hosts}
      - ES_USERNAME=${es_username}
      - ES_PASSWORD=${es_password}
      - APP_CUSTOMER=${app_customer}
      - APP_OWNER=${app_owner}
      - APP_EMAIL=${app_email}
      - APP_ENV=${app_env}
      - APP_DEPLOYMENT=${app_deployment}
      - APP_REPO=${app_repo}
      - APP_MODULE=${app_module}
      - APP_RESOURCE_GROUP=${app_resource_group}

volumes:
  nexus_log_vol:
    driver: local
  filebeat_vol:
    driver: local