version: "3.9"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:${influxdb_tag}
    restart: always
    labels:
      service: influxdb
    volumes:
      - ${influxdb_data_path}:/var/lib/influxdb2
    ports:
      - ${influxdb_port}:8086

  filebeat:
    container_name: filebeat
    image: ${acr_login_server}.azurecr.io/filebeat:${filebeat_tag}
    user: root
    restart: always
    labels:
      service: filebeat 
    volumes:
      - filebeat_vol:/var/log
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/cloud-init-output.log:/var/log/hostlogs/cloud-init/cloud-init-output.log
    environment:
      - ES_HOSTS=${es_hosts}
      - ES_USERNAME=${es_username}
      - ES_PASSWORD=${es_password}
      - APP_CUSTOMER=${app_customer}
      - APP_OWNER=${app_owner}
      - APP_EMAIL=${app_email}
      - APP_ENV=${app_env}
      - APP_DEPLOYMENT=${app_deployment}
      - APP_REPO=${app_repo}
      - APP_MODULE=${app_module}
      - APP_RESOURCE_GROUP=${app_resource_group}

volumes:
  filebeat_vol:
    driver: local